spring.application.name=ms-detection-backend

# SERVER
server.port=${PORT:8080}

# MONGODB
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=ms_detection

# MONGODB LOGGING
logging.level.org.mongodb.driver.cluster=WARN
logging.level.org.mongodb.driver.connection=WARN

# FILE UPLOAD
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# ML API
ml.api.url=${ML_API_URL}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mk2151431@gmail.com
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com