spring.application.name=ms-detection-backend

server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=ms_detection

logging.level.org.mongodb.driver.cluster=WARN
logging.level.org.mongodb.driver.connection=WARN

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

ml.api.url=${ML_API_URL}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mk2151431@gmail.com
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration